This is some of the class notes and practice codes from the Machine Learning class I am taking

In [1]:
#Import Libraries 

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


data = pd.read_csv('tennis.csv')
data.head()

outlook  temperature  humidity  windy play
0     sunny           85        85  False   no
1     sunny           80        90   True   no
2  overcast           83        86  False  yes
3     rainy           70        96  False  yes
4     rainy           68        80  False  yes

Data Preprocessing 

Handling the categorical data:
-even though I do not need to apply the label encoder to all of the data, it just saves time for me to apply it all and then get the column I need afterwards (which is the outlook column, after the label encoder, I will go ahead and apply one hot encoder)

In [8]:
#encoder:  Categoric -> Numeric
from sklearn.preprocessing import LabelEncoder
data2 = data.apply(LabelEncoder().fit_transform)
c = data2.iloc[:,:1]

print(c)

    outlook
0         2
1         2
2         0
3         1
4         1
5         1
6         0
7         2
8         2
9         1
10        2
11        0
12        0
13        1


In [9]:
#One Hot encoder
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categorical_features='all')
c=ohe.fit_transform(c).toarray()
print(c)

[[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [10]:
weather = pd.DataFrame(data = c, index = range(14), columns=['o','r','s'])
print(weather)

      o    r    s
0   0.0  0.0  1.0
1   0.0  0.0  1.0
2   1.0  0.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   1.0  0.0  0.0
7   0.0  0.0  1.0
8   0.0  0.0  1.0
9   0.0  1.0  0.0
10  0.0  0.0  1.0
11  1.0  0.0  0.0
12  1.0  0.0  0.0
13  0.0  1.0  0.0


In [14]:
final_data = pd.concat([weather,data.iloc[:,1:3]],axis = 1)
print(final_data)

      o    r    s  temperature  humidity
0   0.0  0.0  1.0           85        85
1   0.0  0.0  1.0           80        90
2   1.0  0.0  0.0           83        86
3   0.0  1.0  0.0           70        96
4   0.0  1.0  0.0           68        80
5   0.0  1.0  0.0           65        70
6   1.0  0.0  0.0           64        65
7   0.0  0.0  1.0           72        95
8   0.0  0.0  1.0           69        70
9   0.0  1.0  0.0           75        80
10  0.0  0.0  1.0           75        70
11  1.0  0.0  0.0           72        90
12  1.0  0.0  0.0           81        75
13  0.0  1.0  0.0           71        91


In [15]:
final_data = pd.concat([data2.iloc[:,-2:],final_data], axis = 1)
print(final_data)

    windy  play    o    r    s  temperature  humidity
0       0     0  0.0  0.0  1.0           85        85
1       1     0  0.0  0.0  1.0           80        90
2       0     1  1.0  0.0  0.0           83        86
3       0     1  0.0  1.0  0.0           70        96
4       0     1  0.0  1.0  0.0           68        80
5       1     0  0.0  1.0  0.0           65        70
6       1     1  1.0  0.0  0.0           64        65
7       0     0  0.0  0.0  1.0           72        95
8       0     1  0.0  0.0  1.0           69        70
9       0     1  0.0  1.0  0.0           75        80
10      1     1  0.0  0.0  1.0           75        70
11      1     1  1.0  0.0  0.0           72        90
12      0     1  1.0  0.0  0.0           81        75
13      1     0  0.0  1.0  0.0           71        91


In [16]:
#Test train split 
from sklearn.cross_validation import train_test_split
x_train, x_test,y_train,y_test = train_test_split(final_data.iloc[:,:-1],final_data.iloc[:,-1:],test_size=0.33, random_state=0)


/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [17]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)


y_pred = regressor.predict(x_test)

print(y_pred)


[[84.45365573]
 [63.93839954]
 [85.76050662]
 [64.21013241]
 [75.06793322]]


In [18]:
import statsmodels.formula.api as sm 
X = np.append(arr = np.ones((14,1)).astype(int), values=final_data.iloc[:,:-1], axis=1 )
X_l = final_data.iloc[:,[0,1,2,3,4,5]].values
r_ols = sm.OLS(endog = final_data.iloc[:,-1:], exog =X_l)
r = r_ols.fit()
print(r.summary())

                            OLS Regression Results                            
Dep. Variable:               humidity   R-squared:                       0.294
Model:                            OLS   Adj. R-squared:                 -0.148
Method:                 Least Squares   F-statistic:                    0.6653
Date:                Sat, 02 Feb 2019   Prob (F-statistic):              0.661
Time:                        22:26:10   Log-Likelihood:                -49.542
No. Observations:                  14   AIC:                             111.1
Df Residuals:                       8   BIC:                             114.9
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -4.0286      7.229     -0.557      0.5

/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py:1394: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  "anyway, n=%i" % int(n))


In [19]:
final_data = final_data.iloc[:,1:]

In [20]:
import statsmodels.formula.api as sm 
X = np.append(arr = np.ones((14,1)).astype(int), values=final_data.iloc[:,:-1], axis=1 )
X_l = final_data.iloc[:,[0,1,2,3,4]].values
r_ols = sm.OLS(endog = final_data.iloc[:,-1:], exog =X_l)
r = r_ols.fit()
print(r.summary())

                            OLS Regression Results                            
Dep. Variable:               humidity   R-squared:                       0.266
Model:                            OLS   Adj. R-squared:                 -0.060
Method:                 Least Squares   F-statistic:                    0.8165
Date:                Sat, 02 Feb 2019   Prob (F-statistic):              0.546
Time:                        22:26:17   Log-Likelihood:                -49.809
No. Observations:                  14   AIC:                             109.6
Df Residuals:                       9   BIC:                             112.8
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -6.2865      6.909     -0.910      0.3

/anaconda3/lib/python3.6/site-packages/scipy/stats/stats.py:1394: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  "anyway, n=%i" % int(n))


In [21]:
x_train = x_train.iloc[:,1:]
x_test = x_test.iloc[:,1:]

regressor.fit(x_train,y_train)


y_pred = regressor.predict(x_test)